Added missing steps to publish

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -14,19 +14,19 @@ jobs:
       matrix:
         include:
           # Windows
-          - { os: windows-latest, arch: x64,   rid: win-x64,   output_path: build/Release/uv.dll, file-name: libuv.dll, cmake_args: '-A x64' }
-          - { os: windows-latest, arch: Win32, rid: win-x86,   output_path: build/Release/uv.dll, file-name: libuv.dll, cmake_args: '-A Win32' }
-          - { os: windows-latest, arch: arm64, rid: win-arm64, output_path: build/Release/uv.dll, file-name: libuv.dll, cmake_args: '-A arm64' }
-          
+          - { os: windows-latest, arch: x64,   rid: win-x64,   output_path: build/Release/uv.dll, file-name: libuv.dll, cmake_args: '-A x64',   build_testing: 'ON',  allowed_failures: 0 }
+          - { os: windows-latest, arch: Win32, rid: win-x86,   output_path: build/Release/uv.dll, file-name: libuv.dll, cmake_args: '-A Win32', build_testing: 'ON',  allowed_failures: 0 }
+          - { os: windows-latest, arch: arm64, rid: win-arm64, output_path: build/Release/uv.dll, file-name: libuv.dll, cmake_args: '-A arm64', build_testing: 'OFF', allowed_failures: 0 }
+
           # Linux (Ubuntu builds generic .so)
-          - { os: ubuntu-latest,  arch: x64,   rid: linux-x64, output_path: build/libuv.so, file-name: libuv.so }
-          - { os: ubuntu-latest,  arch: arm64, rid: linux-arm64, output_path: build/libuv.so, file-name: libuv.so, cmake_args: '-DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc' }
-          - { os: ubuntu-latest,  arch: arm,   rid: linux-arm,   output_path: build/libuv.so, file-name: libuv.so, cmake_args: '-DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc' }
-          - { os: ubuntu-latest,  arch: armel, rid: linux-armel, output_path: build/libuv.so, file-name: libuv.so, cmake_args: '-DCMAKE_C_COMPILER=arm-linux-gnueabi-gcc' }
+          - { os: ubuntu-latest, arch: x64,   rid: linux-x64,   output_path: build/libuv.so, file-name: libuv.so, build_testing: 'ON',  allowed_failures: 0 }
+          - { os: ubuntu-latest, arch: arm64, rid: linux-arm64, output_path: build/libuv.so, file-name: libuv.so, cmake_args: '-DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++', build_testing: 'ON',  allowed_failures: 6 }
+          - { os: ubuntu-latest, arch: arm,   rid: linux-arm,   output_path: build/libuv.so, file-name: libuv.so, cmake_args: '-DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++', build_testing: 'ON',  allowed_failures: 6 }
+          - { os: ubuntu-latest, arch: armel, rid: linux-armel, output_path: build/libuv.so, file-name: libuv.so, cmake_args: '-DCMAKE_C_COMPILER=arm-linux-gnueabi-gcc -DCMAKE_CXX_COMPILER=arm-linux-gnueabi-g++',   build_testing: 'OFF', allowed_failures: 0 }
 
           # macOS (Universal binary or specific)
-          - { os: macos-latest,   arch: x64,   rid: osx-x64,   output_path: build/libuv.dylib, file-name: libuv.dylib, cmake_args: '-DCMAKE_OSX_ARCHITECTURES=x86_64' }
-          - { os: macos-latest,   arch: arm64, rid: osx-arm64, output_path: build/libuv.dylib, file-name: libuv.dylib, cmake_args: '-DCMAKE_OSX_ARCHITECTURES=arm64' }
+          - { os: macos-latest, arch: x64,   rid: osx-x64,   output_path: build/libuv.dylib, file-name: libuv.dylib, cmake_args: '-DCMAKE_OSX_ARCHITECTURES=x86_64', build_testing: 'ON', allowed_failures: 5 }
+          - { os: macos-latest, arch: arm64, rid: osx-arm64, output_path: build/libuv.dylib, file-name: libuv.dylib, cmake_args: '-DCMAKE_OSX_ARCHITECTURES=arm64',   build_testing: 'ON', allowed_failures: 5 }
     steps:
       - name: Checkout code
         uses: actions/checkout@v6
@@ -38,20 +38,54 @@ jobs:
         run: |
           sudo apt-get update
           if [ "${{ matrix.rid }}" == "linux-arm64" ]; then
-            sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
+            sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu qemu-user-static
           elif [ "${{ matrix.rid }}" == "linux-arm" ]; then
-            sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
+            sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf qemu-user-static
           elif [ "${{ matrix.rid }}" == "linux-armel" ]; then
             sudo apt-get install -y gcc-arm-linux-gnueabi g++-arm-linux-gnueabi
           fi
+
+      - name: Fix CMakeLists.txt
+        if: matrix.rid == 'win-arm64'
+        working-directory: libuv
+        shell: pwsh
+        run: |
+          (Get-Content -path 'CMakeLists.txt' -Raw) | %{ $_.Replace('if(WIN32)', "if(CMAKE_GENERATOR_PLATFORM MATCHES `"ARM|ARM64`")`r`n  list(APPEND uv_test_libraries shell32)`r`nendif()`r`n`r`nif(WIN32)") } | Set-Content -Path 'CMakeLists.txt'
 
       - name: Build Project
         uses: threeal/cmake-action@v2.1.0
         with:
           source-dir: libuv
           build-dir: build
-          args: ${{ matrix.cmake_args }} -DBUILD_TESTING=OFF
+          args: ${{ matrix.cmake_args }} -DBUILD_TESTING=${{ matrix.build_testing }}
           build-args: '--config Release'
+
+      - name: Run tests
+        if: matrix.build_testing == 'ON'
+        shell: bash
+        run: |
+          set +e
+          if [[ "${{ matrix.rid }}" == "linux-arm64" ]]; then
+            QEMU_LD_PREFIX=/usr/aarch64-linux-gnu qemu-aarch64-static ./build/uv_run_tests
+          elif [[ "${{ matrix.rid }}" == "linux-arm" ]]; then
+            QEMU_LD_PREFIX=/usr/arm-linux-gnueabihf qemu-arm-static ./build/uv_run_tests
+          elif [[ "${{ matrix.rid }}" == "linux-x64" ]]; then
+            ./build/uv_run_tests
+          elif [[ "${{ matrix.rid }}" == win-* ]]; then
+            build/Release/uv_run_tests.exe
+          else
+            build/Release/uv_run_tests
+          fi
+          ret=$?
+          set -e
+          if [ $ret -eq 0 ]; then
+            echo "All tests succeeded"
+          elif [ $ret -le ${{ matrix.allowed_failures }} ]; then
+            echo "::warning::$ret tests failed, known issues"
+          else
+            echo "$ret tests failed"
+            exit $ret
+          fi
 
       - name: Prepare Artifact Directory
         shell: bash
@@ -71,11 +105,12 @@ jobs:
   create-nuget:
     name: Create NuGet Package
     needs: build
-    if: startsWith(github.ref, 'refs/tags/v')
     runs-on: windows-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v6
+        with:
+          submodules: true
 
       - name: Download all artifacts
         uses: actions/download-artifact@v6
@@ -89,8 +124,38 @@ jobs:
           # all-artifacts contains folders named after RIDs (win-x64, linux-x64, etc.)
           cp -r all-artifacts/* nuget_root/runtimes/
 
+      - name: Update change log in nuspec
+        shell: pwsh
+        run: |
+          $first = $false
+          $changeLog = ""
+          $path = Join-Path (Join-Path (Get-Location) 'libuv') 'ChangeLog'
+          $nuspec = Join-Path (Get-Location) 'libuv-shared.nuspec'
+
+          foreach($line in Get-Content -Path $path)
+          {
+              if($line -match '\d{4}\.\d{2}\.\d{2}.*')
+              {
+                  if($first) { break; }
+                  $first = $true
+              }
+
+              if($first -and ![String]::IsNullOrWhiteSpace($line))
+              {
+                  $changeLog += $line
+                  $changeLog += [System.Environment]::NewLine
+              }
+          }
+
+          [xml]$xml = Get-Content $nuspec
+          $xml.package.metadata.releaseNotes = $changeLog
+          $xml.Save($nuspec)
+
       - name: Setup NuGet
         uses: NuGet/setup-nuget@v2
+
+      - name: Configure NuGet authentication
+        run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
 
       - name: Pack NuGet
         shell: bash
@@ -107,6 +172,13 @@ jobs:
         with:
           name: nuget-package
           path: "*.nupkg"
+
+      - name: NuGet push to GitHub Packages
+        run: dotnet nuget push *.nupkg --source github
+
+      - name: NuGet push to nuget.org
+        if: startsWith(github.ref, 'refs/tags/v')
+        run: nuget push *.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET_API_KEY }}
 
 
   create-release:
